version: '3.3'

networks:
  pmt-network:
    driver: bridge

volumes:
  prometheus_data:

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - pmt-network
    ports:
      - 9090:9090