global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-cep-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['${HOST}:8081']
        labels:
          application: "api-cep"