global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-cep-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8081"]
        labels:
          application: "api-cep"